version: '3'
services:
  wikidb:
    image: mongo:3
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - /data/mongo:/data/db
  wikijs:
    image: 'requarks/wiki:latest'
    command: 'supervisord --nodaemon --user=root -c /etc/supervisord.conf'
    links:
      - wikidb
    depends_on:
      - wikidb
    ports:
      - '3080:8085'
    environment:
      WIKI_ADMIN_EMAIL: admin@wikijs.com
    volumes:
      - /var/wiki/wikijs.config.yaml:/var/wiki/config.yml
